// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_CLONE_COFFERAPP
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_CLONE_COFFERAPP
uint64_t uniffi_cf_ffi_fn_clone_cofferapp(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_FREE_COFFERAPP
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_FREE_COFFERAPP
void uniffi_cf_ffi_fn_free_cofferapp(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_CONSTRUCTOR_COFFERAPP_NEW
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_CONSTRUCTOR_COFFERAPP_NEW
uint64_t uniffi_cf_ffi_fn_constructor_cofferapp_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_COFFERAPP_CREATE_VAULT
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_COFFERAPP_CREATE_VAULT
RustBuffer uniffi_cf_ffi_fn_method_cofferapp_create_vault(uint64_t ptr, RustBuffer base_dir, RustBuffer name, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_COFFERAPP_LIST_VAULTS
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_COFFERAPP_LIST_VAULTS
RustBuffer uniffi_cf_ffi_fn_method_cofferapp_list_vaults(uint64_t ptr, RustBuffer base_dir, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_COFFERAPP_LOCK_ALL
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_COFFERAPP_LOCK_ALL
void uniffi_cf_ffi_fn_method_cofferapp_lock_all(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_COFFERAPP_OPEN_VAULT
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_COFFERAPP_OPEN_VAULT
uint64_t uniffi_cf_ffi_fn_method_cofferapp_open_vault(uint64_t ptr, RustBuffer base_dir, RustBuffer vault_uuid, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_CLONE_VAULTSESSION
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_CLONE_VAULTSESSION
uint64_t uniffi_cf_ffi_fn_clone_vaultsession(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_FREE_VAULTSESSION
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_FREE_VAULTSESSION
void uniffi_cf_ffi_fn_free_vaultsession(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_AUTO_LOCK_IF_EXPIRED
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_AUTO_LOCK_IF_EXPIRED
int8_t uniffi_cf_ffi_fn_method_vaultsession_auto_lock_if_expired(uint64_t ptr, int64_t now_secs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_CREATE_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_CREATE_ITEM
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_create_item(uint64_t ptr, RustBuffer draft, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_DELETE_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_DELETE_ITEM
void uniffi_cf_ffi_fn_method_vaultsession_delete_item(uint64_t ptr, RustBuffer item_id, int8_t hard, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_DISPLAY_NAME
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_DISPLAY_NAME
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_display_name(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_GENERATE_PASSWORD
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_GENERATE_PASSWORD
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_generate_password(uint64_t ptr, RustBuffer opts, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_GET_FIELD_VALUE
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_GET_FIELD_VALUE
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_get_field_value(uint64_t ptr, RustBuffer item_id, RustBuffer field_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_GET_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_GET_ITEM
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_get_item(uint64_t ptr, RustBuffer item_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_IMPORT_CSV
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_IMPORT_CSV
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_import_csv(uint64_t ptr, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_IS_UNLOCKED
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_IS_UNLOCKED
int8_t uniffi_cf_ffi_fn_method_vaultsession_is_unlocked(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_LIST_ITEMS
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_LIST_ITEMS
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_list_items(uint64_t ptr, RustBuffer filter, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_LOCK
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_LOCK
void uniffi_cf_ffi_fn_method_vaultsession_lock(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_PARSE_OTPAUTH_URI
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_PARSE_OTPAUTH_URI
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_parse_otpauth_uri(uint64_t ptr, RustBuffer uri, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_PRECHECK_CSV
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_PRECHECK_CSV
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_precheck_csv(uint64_t ptr, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_RESTORE_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_RESTORE_ITEM
void uniffi_cf_ffi_fn_method_vaultsession_restore_item(uint64_t ptr, RustBuffer item_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_SEARCH
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_search(uint64_t ptr, RustBuffer query, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_SET_FAVORITE
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_SET_FAVORITE
void uniffi_cf_ffi_fn_method_vaultsession_set_favorite(uint64_t ptr, RustBuffer item_id, int8_t favorite, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_SET_IDLE_TIMEOUT_SECS
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_SET_IDLE_TIMEOUT_SECS
void uniffi_cf_ffi_fn_method_vaultsession_set_idle_timeout_secs(uint64_t ptr, int64_t secs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_SET_LAST_ACTIVITY
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_SET_LAST_ACTIVITY
void uniffi_cf_ffi_fn_method_vaultsession_set_last_activity(uint64_t ptr, int64_t unix_secs, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_STRENGTH_ESTIMATE
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_STRENGTH_ESTIMATE
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_strength_estimate(uint64_t ptr, RustBuffer candidate, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_TOTP_CODE
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_TOTP_CODE
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_totp_code(uint64_t ptr, RustBuffer item_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_UNLOCK
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_UNLOCK
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_unlock(uint64_t ptr, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_UPDATE_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_UPDATE_ITEM
void uniffi_cf_ffi_fn_method_vaultsession_update_item(uint64_t ptr, RustBuffer item_id, RustBuffer draft, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_VAULT_DIR
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_VAULT_DIR
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_vault_dir(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_VAULT_UUID
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_FN_METHOD_VAULTSESSION_VAULT_UUID
RustBuffer uniffi_cf_ffi_fn_method_vaultsession_vault_uuid(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_cf_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_cf_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUSTBUFFER_FREE
void ffi_cf_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_cf_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_U8
void ffi_cf_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_U8
void ffi_cf_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_U8
void ffi_cf_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_cf_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_I8
void ffi_cf_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_I8
void ffi_cf_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_I8
void ffi_cf_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_cf_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_U16
void ffi_cf_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_U16
void ffi_cf_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_U16
void ffi_cf_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_cf_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_I16
void ffi_cf_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_I16
void ffi_cf_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_I16
void ffi_cf_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_cf_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_U32
void ffi_cf_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_U32
void ffi_cf_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_U32
void ffi_cf_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_cf_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_I32
void ffi_cf_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_I32
void ffi_cf_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_I32
void ffi_cf_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_cf_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_U64
void ffi_cf_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_U64
void ffi_cf_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_U64
void ffi_cf_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_cf_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_I64
void ffi_cf_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_I64
void ffi_cf_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_I64
void ffi_cf_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_cf_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_F32
void ffi_cf_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_F32
void ffi_cf_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_F32
void ffi_cf_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_cf_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_F64
void ffi_cf_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_F64
void ffi_cf_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_F64
void ffi_cf_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_cf_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_cf_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_cf_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_cf_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_cf_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_POLL_VOID
void ffi_cf_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_cf_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_FREE_VOID
void ffi_cf_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_CF_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_cf_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_COFFERAPP_CREATE_VAULT
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_COFFERAPP_CREATE_VAULT
uint16_t uniffi_cf_ffi_checksum_method_cofferapp_create_vault(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_COFFERAPP_LIST_VAULTS
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_COFFERAPP_LIST_VAULTS
uint16_t uniffi_cf_ffi_checksum_method_cofferapp_list_vaults(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_COFFERAPP_LOCK_ALL
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_COFFERAPP_LOCK_ALL
uint16_t uniffi_cf_ffi_checksum_method_cofferapp_lock_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_COFFERAPP_OPEN_VAULT
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_COFFERAPP_OPEN_VAULT
uint16_t uniffi_cf_ffi_checksum_method_cofferapp_open_vault(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_AUTO_LOCK_IF_EXPIRED
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_AUTO_LOCK_IF_EXPIRED
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_auto_lock_if_expired(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_CREATE_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_CREATE_ITEM
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_create_item(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_DELETE_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_DELETE_ITEM
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_delete_item(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_DISPLAY_NAME
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_DISPLAY_NAME
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_display_name(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_GENERATE_PASSWORD
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_GENERATE_PASSWORD
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_generate_password(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_GET_FIELD_VALUE
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_GET_FIELD_VALUE
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_get_field_value(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_GET_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_GET_ITEM
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_get_item(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_IMPORT_CSV
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_IMPORT_CSV
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_import_csv(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_IS_UNLOCKED
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_IS_UNLOCKED
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_is_unlocked(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_LIST_ITEMS
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_LIST_ITEMS
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_list_items(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_LOCK
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_LOCK
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_lock(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_PARSE_OTPAUTH_URI
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_PARSE_OTPAUTH_URI
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_parse_otpauth_uri(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_PRECHECK_CSV
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_PRECHECK_CSV
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_precheck_csv(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_RESTORE_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_RESTORE_ITEM
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_restore_item(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_SEARCH
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_search(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_SET_FAVORITE
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_SET_FAVORITE
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_set_favorite(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_SET_IDLE_TIMEOUT_SECS
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_SET_IDLE_TIMEOUT_SECS
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_set_idle_timeout_secs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_SET_LAST_ACTIVITY
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_SET_LAST_ACTIVITY
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_set_last_activity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_STRENGTH_ESTIMATE
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_STRENGTH_ESTIMATE
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_strength_estimate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_TOTP_CODE
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_TOTP_CODE
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_totp_code(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_UNLOCK
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_UNLOCK
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_unlock(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_UPDATE_ITEM
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_UPDATE_ITEM
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_update_item(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_VAULT_DIR
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_VAULT_DIR
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_vault_dir(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_VAULT_UUID
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_METHOD_VAULTSESSION_VAULT_UUID
uint16_t uniffi_cf_ffi_checksum_method_vaultsession_vault_uuid(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_CONSTRUCTOR_COFFERAPP_NEW
#define UNIFFI_FFIDEF_UNIFFI_CF_FFI_CHECKSUM_CONSTRUCTOR_COFFERAPP_NEW
uint16_t uniffi_cf_ffi_checksum_constructor_cofferapp_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CF_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_CF_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_cf_ffi_uniffi_contract_version(void
    
);
#endif

