[package]
name = "cf-totp"
description = "Coffer TOTP (RFC 6238 compliant)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hmac = { workspace = true }
sha1 = { workspace = true }
sha2 = "0.10"
urlencoding = "2.1"

[dev-dependencies]
criterion = "0.5"
